name = "ReturnAssumptions"
uuid = "87a85c3b-363c-4537-9dfe-815be5101fbb"
authors = ["John Stevens"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
